### ISSUE TITLE
First Time User issue

### ISSUE THREAD

**Issue by jtrunick** [swannodette/hello-cljsc#6]
I installed Lein (2.3.4) - available on command line
installed LT (0.6.2)

Open the core.clj file click Command-Enter and I get:
clojure.lang.ExceptionInfo: Invalid token: ::ana/namespaces
            core.clj:4327 clojure.core/ex-info
     reader_types.clj:238 ibdknox.tools.reader.reader-types/reader-error
          RestFn.java:439 clojure.lang.RestFn.invoke

New to everything here, so newbie mistake I imagine... Do I need to install Clojure/Script somehow?

**Comment by swannodette** [comment]
Do you mean "typing Command-Enter"? Where are you placing your cursor when you do this?

**Comment by jtrunick** [comment]
At the end of the first function.

**Comment by jtrunick** [comment]
well oddly now it seems to work. i did lein cljsbuild ... not sure if that helped or just clicking around a bit.
